/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge16;

import challenge16.data.BTNode;
import challenge16.structure.BinaryTree;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void HappyPath() {
        BinaryTree binaryTree = new BinaryTree();
        binaryTree.setRoot(new BTNode(1));
        binaryTree.getRoot().setLeft(new BTNode<Integer>(3));
        binaryTree.getRoot().setRight(new BTNode<Integer>(12));
        binaryTree.getRoot().getLeft().setLeft(new BTNode<Integer>(6));
        binaryTree.getRoot().getLeft().setRight(new BTNode<Integer>(7));
        binaryTree.getRoot().getLeft().getLeft().setLeft(new BTNode<Integer>(9));
        assertEquals(12, binaryTree.Max());
    }

    @Test void treeIsEmpty() {
        BinaryTree binaryTree = new BinaryTree();

        assertEquals(0, binaryTree.Max());
    }
}
