/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void happyPath() {
        int [] arr = {1, 4, 5, 2};
        int [] array = App.InsertionSort(arr);
        assertEquals(2, array[1]);
    }

    @ Test void emptyArray () {
        int [] arr = {};
        int [] array = App.InsertionSort(arr);
        assertEquals(0, array.length);
    }
}
