/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge16;

import challenge16.data.BTNode;
import challenge16.structure.BinaryTree;

public class App {

    public static void main(String[] args) {
        BinaryTree binaryTree = new BinaryTree();
        binaryTree.setRoot(new BTNode(1));
        binaryTree.getRoot().setLeft(new BTNode<Integer>(3));
        binaryTree.getRoot().setRight(new BTNode<Integer>(12));
        binaryTree.getRoot().getLeft().setLeft(new BTNode<Integer>(6));
        binaryTree.getRoot().getLeft().setRight(new BTNode<Integer>(7));
        binaryTree.getRoot().getLeft().getLeft().setLeft(new BTNode<Integer>(9));

        System.out.println(binaryTree.Max());
    }
}
