/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge30;

import challenge30.structure.HashMap;

public class App {

    public static void main(String[] args) {
        HashMap<String, String> hashCode = new HashMap<>();
        hashCode.set("0", "Mohammad");
        hashCode.set("1", "emad");
        hashCode.set("2", "sara");
        hashCode.set("3", "iyad");
        hashCode.set("4", "Mohammad");
        hashCode.set("5", "yousef");
        hashCode.set("6", "sara");
        hashCode.set("7", "iyad");
        hashCode.set("8", "Mohammad");
        hashCode.set("9", "yousef");
        hashCode.set("10", "sara");
        hashCode.set("11", "iyad");
        hashCode.set("12", "Mohammad");
        hashCode.set("13", "yousef");
        System.out.println(hashCode.get("3"));
        System.out.println(hashCode.contains("1"));
        System.out.println(hashCode.keys());
        System.out.println(hashCode.hash("1"));// 3
        System.out.println(hashCode.getBuckets());

        // RepeatedWord
        Algorithm algorithm = new Algorithm();
        String text = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        System.out.println(algorithm.repeatedWord(text));


        // LeftJoin
        HashMap<String, String> hashMap1 = new HashMap<>();
        HashMap<String, String> hashMap2 = new HashMap<>();

        hashMap1.set("1", "11");
        hashMap1.set("2", "22");
        hashMap1.set("3", "33");
        hashMap1.set("9", "1");
        hashMap1.set("7", "33");

        hashMap2.set("1", "1");
        hashMap2.set("2", "4");
        hashMap2.set("3", "9");
        hashMap2.set("6", "1");
        hashMap2.set("10", "1");

        System.out.println(algorithm.leftJoin(hashMap1, hashMap2));

    }
}
