/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

public class App {

    public static void main(String[] args) {
        int [] num = {1, 3, 2, 5, 4};
        int [] arr = InsertionSort(num);
        for (int i = 0; i < arr.length ; i++){
            System.out.println(arr[i]);
        }
    }

    public static int[] InsertionSort(int [] array){
        for (int i = 1; i < array.length; i++){
            int j = i-1;
            int temp = array[i];
            while (j >= 0 & temp < array[j]){
                array[j + 1] = array[j];
                j = j - 1;
            }
            array[j + 1] = temp;
        }
        return array;
    }
}
