/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package New.folder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void HappyPath() {
        K_AryTree tree = new K_AryTree(new Node(1));
        tree.getRoot().addChild(2);
        tree.getRoot().addChild(3);
        tree.getRoot().addChild(4);
        tree.getRoot().addChild(5);
        tree.getRoot().getChild().get(0).addChild(6);
        tree.getRoot().getChild().get(0).addChild(7);
        tree.getRoot().getChild().get(0).addChild(8);

        assertEquals(8, tree.fizzBuzz(tree).getAllData().size());
    }

    @Test
    void edgeCase () {
        K_AryTree tree = new K_AryTree(new Node(1));
        assertEquals(1, tree.getRoot());
    }



}
