/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge41;

import challenge41.algorthims.Algorithms;

public class App {

    public static void main(String[] args) {

        Algorithms algorithm = new Algorithms();
        String s = "Moha  moa noa ";

        System.out.println(algorithm.anagramString("Astronomers", "Moon starers"));
        System.out.println(algorithm.reverseText(s));
    }


}
