/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

import challenge10.QueueStructure.Queue;
import challenge10.QueueStructure.QueueNode;
import challenge10.StackStructure.Stack;
import challenge10.StackStructure.StackNode;

public class App {

    public static void main(String[] args) {

        // Stack Instance
        Stack  stack = new Stack();
        stack.push(new StackNode<>(1));
        stack.push(new StackNode<>(2));
        stack.push(new StackNode<>(3));
        stack.push(new StackNode<>(4));
        stack.push(new StackNode<>(5));
        System.out.println(stack.toString());
//        System.out.println("The Element At The Top Of The Stack Is : " + stack.peek());
//        System.out.println("The Top After we call pop() method : " + stack.pop());
//        System.out.println(stack.toString());
//        System.out.println("The Element At The Top Of The Stack Is : " + stack.peek());

        Queue queue = new Queue();
        queue.enqueue(new QueueNode<>(1));
        queue.enqueue(new QueueNode<>(2));
        queue.enqueue(new QueueNode<>(3));
        queue.enqueue(new QueueNode<>(4));
        queue.enqueue(new QueueNode<>(5));
        System.out.println(queue);
    }
}
