/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge27;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void happyPath() {
        int [] arr  = {1, 4, 5, 2, 3};
        int [] arr2 = App.MargeSort (arr, 0, arr.length - 1);

        assertEquals(1, arr2[0]);
        assertEquals(2, arr2[1]);
        assertEquals(3, arr2[2]);
        assertEquals(4, arr2[3]);
        assertEquals(5, arr2[4]);
    }

    @Test
    void oneElementArray () {
        int [] arr = {1};
        int [] arr2 = App.MargeSort (arr, 0, arr.length - 1);
        assertEquals(true, arr[0] == arr2[0]);
    }

    @Test
    void emptyArray () {
        int [] arr = {};
        int [] arr2 = App.MargeSort (arr, 0, arr.length - 1);
        assertEquals(0, arr2.length);
    }
}
