/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import challenge7.linkedList.LinkedList;

public class App {

    public static void main(String[] args) {

        LinkedList <Integer> linkedList = new LinkedList();
        linkedList.addNode(1);
        linkedList.addNode(2);
        linkedList.addNode(3);
        linkedList.addNode(4);
        linkedList.printItem();
//        System.out.println(linkedList.getCount());
        System.out.println(linkedList.kthFromEnd(0));
    }

}
