/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge8;

public class App {

    public static void main(String[] args) {
        // First LinkedList instance
        FirstLinkedList <Integer> firstLinkedList = new FirstLinkedList<>();
        firstLinkedList.addNode(1);
        firstLinkedList.addNode(3);
        firstLinkedList.addNode(5);
        firstLinkedList.addNode(7);
        firstLinkedList.printNodes("First");

        // Second LinkedList
        FirstLinkedList <Integer> secondLinkedList = new FirstLinkedList<>();
        secondLinkedList.addNode(2);
        secondLinkedList.addNode(4);
        secondLinkedList.addNode(6);
        secondLinkedList.addNode(8);
        secondLinkedList.printNodes("Second");

        // Result LinkedList
        FirstLinkedList resultLinkedList = firstLinkedList.zipLists(firstLinkedList, secondLinkedList);
        resultLinkedList.printNodes("Result");
    }
}
