/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package New.folder;

public class App {

    public static void main(String[] args) {
        K_AryTree tree = new K_AryTree(new Node(1));
        tree.getRoot().addChild(2);
        tree.getRoot().addChild(3);
        tree.getRoot().addChild(4);
        tree.getRoot().addChild(5);
        tree.getRoot().getChild().get(0).addChild(6);
        tree.getRoot().getChild().get(0).addChild(7);
        tree.getRoot().getChild().get(0).addChild(8);

        System.out.println("--------------------------- Origin Tree-----------------------");
        tree.print();
        System.out.println();
        System.out.println("-------------------------- Fizz Buzz Tree---------------------");
        tree.fizzBuzz(tree).print();
    }


}
