/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge11;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void enqueueMethod () {
        PseudoQueue pseudoQueue = new PseudoQueue<>();
        pseudoQueue.enqueue(3);
        pseudoQueue.enqueue(5);
        pseudoQueue.enqueue(7);
        pseudoQueue.enqueue(8);
        assertEquals(4, pseudoQueue.getLength());
    }

    @Test
    void dequeueMethod () {
        PseudoQueue pseudoQueue = new PseudoQueue<>();
        pseudoQueue.enqueue(3);
        pseudoQueue.enqueue(5);
        pseudoQueue.enqueue(7);
        pseudoQueue.enqueue(8);
        System.out.println(pseudoQueue.dequeue());
        assertEquals(5, pseudoQueue.getFront().getValue());
    }
}