/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge13;

import challenge13.Stack.Balanced;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void ValidateBracketsMethod () {
        Balanced balanced = new Balanced();
        String result = "";
        String text = "{()}{[]}";
        if (balanced.validateBrackets(text))
            result = "Happy Path";
        else
            result = "Expected";
        assertEquals("Happy Path", result);
    }
}
