/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import challenge7.linkedList.LinkedList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void kGreaterLength () {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.addNode(1);
        linkedList.addNode(2);
        linkedList.addNode(3);
        assertEquals("Exception", linkedList.kthFromEnd(4));
    }

    @Test void KEqualLength () {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.addNode(1);
        linkedList.addNode(2);
        linkedList.addNode(3);
        assertEquals("Exception" , linkedList.kthFromEnd(linkedList.length()));
    }

    @Test void kNotPositive () {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.addNode(1);
        linkedList.addNode(2);
        linkedList.addNode(3);
        assertEquals("Exception", linkedList.kthFromEnd(-1));
    }

    @Test void sizeOne () {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.addNode(1);
        linkedList.addNode(2);
        assertEquals(2, linkedList.length());

    }
    @Test void happyPath () {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.addNode(1);
        linkedList.addNode(2);
        linkedList.addNode(3);
        assertEquals("Happy Path", linkedList.happyPath(1));

    }

}
