/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge11;

public class App {

    public static void main(String[] args) {


        PseudoQueue pseudoQueue = new PseudoQueue<>();
        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(2);
        pseudoQueue.enqueue(3);
        pseudoQueue.enqueue(4);
        pseudoQueue.enqueue(5);
        pseudoQueue.enqueue(6);
        pseudoQueue.enqueue(7);

        pseudoQueue.printQueue();
        System.out.println(pseudoQueue.dequeue());
        System.out.println("__________________________________________________");
        System.out.println("The Front is : " + pseudoQueue.getFront());
        System.out.println("The Rear is  : " + pseudoQueue.getRear());
        pseudoQueue.printQueue();
        System.out.println("__________________________________________________");
        System.out.println("The Front is : " + pseudoQueue.getFront());
        System.out.println("The Rear is  : " + pseudoQueue.getRear());
    }
}
