/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge6;

import challenge6.com.example.LinkedList.LinkedList;

public class App {

    public static void main(String[] args) {
        LinkedList <Integer> linkedList = new LinkedList<>();
        linkedList.append(3);
        linkedList.append(4);
        linkedList.append(6);
        System.out.println(linkedList.insertBefore(9,3));

        linkedList.printItems();
    }
}
