/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge35;

import challenge35.data.Vertex;
import challenge35.structure.Graph;

public class App {

    public static void main(String[] args) {

        // Graph Instance
        Graph  graph = new Graph();
        System.out.println(graph.addNode("A"));
        System.out.println(graph.addNode("B"));
        System.out.println(graph.addNode("C"));
        System.out.println(graph.addNode("D"));
        System.out.println(graph.getNode());
        graph.addEdge(new Vertex("A"), new Vertex("B"));
        graph.addEdge(new Vertex("A"), new Vertex("C"));
        graph.addEdge(new Vertex("B"), new Vertex("D"));
        graph.addEdge(new Vertex("D"), new Vertex("C"));
        System.out.println(graph.getNeighbors(new Vertex("A")));
        System.out.println(graph.size());
    }
}
