/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge28;

public class App {


    public static void main(String[] args) {

        int arr[] = {5, 7, 9, 2, 3};
        int resultArr[] = quickSort(arr, 0, arr.length-1);

        for (int i = 0; i < resultArr.length; i++) {
            System.out.print(resultArr[i]+ " ");
        }
    }

    static int[] quickSort(int[] arr, int left, int right)
    {
        if (left < right)
        {
            int position = partition(arr, left, right);
            quickSort(arr, left, position - 1);
            quickSort(arr, position + 1, right);
        }
        return arr;
    }
    static void swap(int[] arr, int low, int j)
    {
        int temp = arr[low];
        arr[low] = arr[j];
        arr[j] = temp;
    }
    static int partition(int[] arr, int left, int right)
    {

        int pivot = arr[right];
        int low = left - 1;
        for(int j = left; j <= right - 1; j++)
        {

            if (arr[j] < pivot)
            {

                low++;
                swap(arr, low, j);
            }
        }
        swap(arr, low + 1, right);
        return (low + 1);
    }



}
